// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_closest_wgps_helper
IntegerVector compute_closest_wgps_helper(NumericVector a, NumericVector b, NumericVector cd, double sc, int nthread);
RcppExport SEXP _CausalGPS_compute_closest_wgps_helper(SEXP aSEXP, SEXP bSEXP, SEXP cdSEXP, SEXP scSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cd(cdSEXP);
    Rcpp::traits::input_parameter< double >::type sc(scSEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_closest_wgps_helper(a, b, cd, sc, nthread));
    return rcpp_result_gen;
END_RCPP
}
// compute_closest_wgps_helper_no_sc
IntegerVector compute_closest_wgps_helper_no_sc(NumericVector a, NumericVector b, int nthread);
RcppExport SEXP _CausalGPS_compute_closest_wgps_helper_no_sc(SEXP aSEXP, SEXP bSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_closest_wgps_helper_no_sc(a, b, nthread));
    return rcpp_result_gen;
END_RCPP
}
// compute_closest_wgps_no_sc_binary_search
IntegerVector compute_closest_wgps_no_sc_binary_search(NumericVector a, NumericVector b, int nthread);
RcppExport SEXP _CausalGPS_compute_closest_wgps_no_sc_binary_search(SEXP aSEXP, SEXP bSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_closest_wgps_no_sc_binary_search(a, b, nthread));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CausalGPS_compute_closest_wgps_helper", (DL_FUNC) &_CausalGPS_compute_closest_wgps_helper, 5},
    {"_CausalGPS_compute_closest_wgps_helper_no_sc", (DL_FUNC) &_CausalGPS_compute_closest_wgps_helper_no_sc, 3},
    {"_CausalGPS_compute_closest_wgps_no_sc_binary_search", (DL_FUNC) &_CausalGPS_compute_closest_wgps_no_sc_binary_search, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CausalGPS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
