# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_closest_wgps_helper <- function(a, b, cd, sc, nthread) {
    .Call(`_CausalGPS_compute_closest_wgps_helper`, a, b, cd, sc, nthread)
}

compute_closest_wgps_helper_no_sc <- function(a, b, nthread) {
    .Call(`_CausalGPS_compute_closest_wgps_helper_no_sc`, a, b, nthread)
}

compute_closest_wgps_no_sc_binary_search <- function(a, b, nthread) {
    .Call(`_CausalGPS_compute_closest_wgps_no_sc_binary_search`, a, b, nthread)
}

